name: CI/CD pipeline for M3 Assignment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: mehedi-self-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install Node
        run: npm install
      
      - name: Run tests & store logs
        run: |
          echo "Running tests..."
          mkdir -p test-results
          npm run check > test-results/test-results.txt
          echo "Tests completed. Logs stored in test-results.txt"
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/test-results.txt
  
  deploy:
    runs-on: mehedi-self-runner
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Display test results
        run: |
          echo "Displaying test results..."
          cat test-results.txt
          echo "Test results displayed successfully."

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install PM2
        run: npm install pm2 -g
      
      - name: Start Application
        run: |
          echo "Starting Application..."
          pm2 kill || true
          pm2 start server.js --name Node-App
      
      - name: Notify deployment success
        run: echo "Deployment successful!"
      